#!C:\FY Projects\Smart_Speak-main_Updated\venv_streamlit\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
